In [ ]:
import numpy as np

In [ ]:
a = [100,20,3,4]
y = list(map(lambda i:i*10,a))

In [ ]:
na = numpy.array(a)
print(na)

[100  20   3   4]


In [ ]:
type(a)

list

In [ ]:
type(na)

numpy.ndarray

In [ ]:
print(na*10)

[1000  200   30   40]


In [ ]:
print(na.dtype)

int64


In [ ]:
nb = np.array(['hi',10,'students'])

In [ ]:
nb.dtype

dtype('<U21')

In [ ]:
n2 = np.array([[1,2,3],[4,5,6]])

In [ ]:
n2

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
n22 = n2

In [ ]:
np.concatenate([n2,n22],axis = 0)

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [ ]:
np.concatenate([n2,n22],axis = 1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [ ]:
np.sort(n2)

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
import pandas as pd

In [ ]:
s = pd.Series([1,2,'a','b'])

In [ ]:
s

0    1
1    2
2    a
3    b
dtype: object